import type { Metadata } from "next";
import { QuestionContextProvider } from "@/context/QuestionContext";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
// import Home from "@/components/Home";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <QuestionContextProvider>
        <body className={inter.className}>
        <Navbar />
        {children}
      </body>
     </QuestionContextProvider>
      
     
     
    </html>
  );
}
